name: CI

on: pull_request

jobs:
  setup_matrix:
    name: 'Setup Test Matrix'
    runs-on: ubuntu-latest
    outputs:
      beaker_setfile_values: ${{ steps.get-outputs.outputs.beaker_setfile_values }}
      beaker_setfile_names: ${{ steps.get-outputs.outputs.beaker_setfile_names }}
      puppet_major_version_numbers: ${{ steps.get-outputs.outputs.puppet_major_versions }}
      puppet_unit_test_matrix: ${{ steps.get-outputs.outputs.puppet_unit_test_matrix }}
    env:
      BUNDLE_WITHOUT: development:test:release
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
      - name: Run rake validate
        run: bundle exec rake validate
      - name: Setup Test Matrix
        id: get-outputs
        run: bundle exec metadata2gha --use-fqdn --pidfile-workaround false

  unit:
    needs: setup_matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson(needs.setup_matrix.outputs.puppet_unit_test_matrix)}}
    env:
      BUNDLE_WITHOUT: development:system_tests:release
      PUPPET_VERSION: "~> ${{ matrix.puppet }}.0"
    name: Puppet ${{ matrix.puppet }} (Ruby ${{ matrix.ruby }})
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake

  acceptance:
    needs: setup_matrix
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: development:test:release
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(needs.setup_matrix.outputs.beaker_setfile_names) }}
        puppet: ${{ fromJson(needs.setup_matrix.outputs.puppet_major_version_numbers) }}
        exclude:
          - os: Ubuntu 20.04
            puppet: 5
    name: Puppet ${{ matrix.puppet }} - ${{ matrix.os }}
    steps:
      - name: Enable IPv6 on docker
        run: |
          echo '{"ipv6":true,"fixed-cidr-v6":"2001:db8:1::/64"}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake beaker
        env:
          BEAKER_PUPPET_COLLECTION: puppet${{ matrix.puppet }}
          BEAKER_setfile: ${{ fromJson(needs.setup_matrix.outputs.beaker_setfile_values)[matrix.os] }}
